// import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import Footer from "@/components/Footer";
import NextTopLoader from 'nextjs-toploader';
import { ToastContainer, toast } from 'react-toastify';
  import 'react-toastify/dist/ReactToastify.css';
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Quotes App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <NextTopLoader color="red" height={3} zIndex={9999999999999}/>
      <ToastContainer />

 <Header/>
        {children}
 <Footer/>
        
        </body>
    </html>
  );
}
